name: Build and test macOS x86_64
on:
  push:
  workflow_dispatch:

concurrency:
  group: mac-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14]
        racket-variant: ['CS']
        racket-version: ['stable']
        include:
          - os: macos-13
            arch: x64
          - os: macos-14
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }} (${{ matrix.arch }}) Racket ${{ matrix.racket-variant }} ${{ matrix.racket-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.14
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}

    - name: Cache Racket packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.racket
          ~/.cache/racket
        key: racket-${{ matrix.racket-variant }}-${{ matrix.racket-version }}-${{ matrix.os }}

    - name: Version info
      run: |
        uname -a
        uname -m
        clang --version
        gcc --version

    - name: Install langs package
      run: raco pkg install --auto ../langs/

    - name: Run tests
      run: raco test -p langs
