name: macOS
on: [push, workflow_dispatch]

concurrency:
  group: macos-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-14, macos-15, macos-15-intel, macos-26]
        racket-variant: ['CS']
        racket-version: ['stable']
    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} / Racket ${{ matrix.racket-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.14
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}

    - name: Version info
      run: |
        uname -a
        uname -m
        clang --version
        gcc --version

    - name: Cache Racket packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.racket
          ~/.cache/racket
          ~/.local/share/racket
          ~/Library/Caches/Racket
        key: racket-${{ matrix.racket-variant }}-${{ matrix.racket-version }}-${{ matrix.os }}

    - name: Install langs package
      run: |
        raco pkg install --auto ../langs/

    - name: Run tests
      run: |
        raco test -p langs
